### ISSUE TITLE
Make formatting optional

### ISSUE THREAD

**Issue by franvarney** [onmodulus/logger#9]
The formatting makes the errors really hard to read during development. They are just a big blob! Can we make the formatting optional?

**Comment by jackboberg** [comment]
can you share an example?

**Comment by franvarney** [comment]
```
2016-02-03T14:15:37.474Z INFO index Starting franvarney-api...
2016-02-03T14:15:37.485Z INFO server/index Server starting at http://localhost:8000
2016-02-03T14:15:37.501Z ERROR handlers/auth uncaughtException: Routes is not defined {"date":"Wed Feb 03 2016 09:15:37 GMT-0500 (EST)","process":{"pid":3958,"uid":501,"gid":20,"cwd":"/Users/francescavarney/Development/Node/franvarney-api","execPath":"/Users/francescavarney/.nvm/versions/node/v4.2.6/bin/node","version":"v4.2.6","argv":["/Users/francescavarney/.nvm/versions/node/v4.2.6/bin/node","/Users/francescavarney/Development/Node/franvarney-api/index"],"memoryUsage":{"rss":154284032,"heapTotal":128050016,"heapUsed":95979288}},"os":{"loadavg":[2.2890625,2.25,2.11181640625],"uptime":3225},"trace":[{"column":16,"file":"index.js","function":null,"line":57,"method":null,"native":false},{"column":20,"file":"/Users/francescavarney/Development/Node/franvarney-api/node_modules/hapi/lib/server.js","function":null,"line":274,"method":null,"native":false},{"column":16,"file":"/Users/francescavarney/Development/Node/franvarney-api/node_modules/hapi/lib/server.js","function":"[object Object].internals.Server.start.internals.Server.initialize.internals.Server._start.internals.Server.stop._invoke.internals.Server._invoke.next [as _invoke]","line":341,"method":"internals.Server.start.internals.Server.initialize.internals.Server._start.internals.Server.stop._invoke.internals.Server._invoke.next [as _invoke]","native":false},{"column":14,"file":"/Users/francescavarney/Development/Node/franvarney-api/node_modules/hapi/lib/server.js","function":null,"line":266,"method":null,"native":false},{"column":25,"file":"/Users/francescavarney/Development/Node/franvarney-api/node_modules/hapi/node_modules/items/lib/index.js","function":"done","line":31,"method":null,"native":false},{"column":9,"file":"/Users/francescavarney/Development/Node/franvarney-api/node_modules/hapi/lib/connection.js","function":"Server.finalize","line":172,"method":"finalize","native":false},{"column":16,"file":"events.js","function":"Server.g","line":260,"method":"g","native":false},{"column":20,"file":"events.js","function":"emitNone","line":72,"method":null,"native":false},{"column":7,"file":"events.js","function":"Server.emit","line":166,"method":"emit","native":false},{"column":10,"file":"net.js","function":"emitListeningNT","line":1263,"method":null,"native":false},{"column":9,"file":"node.js","function":"nextTickCallbackWith1Arg","line":430,"method":null,"native":false},{"column":17,"file":"node.js","function":"process._tickCallback","line":352,"method":"_tickCallback","native":false}],"stack":["ReferenceError: Routes is not defined","    at index.js:57:16","    at /Users/francescavarney/Development/Node/franvarney-api/node_modules/hapi/lib/server.js:274:20","    at [object Object].internals.Server.start.internals.Server.initialize.internals.Server._start.internals.Server.stop._invoke.internals.Server._invoke.next [as _invoke] (/Users/francescavarney/Development/Node/franvarney-api/node_modules/hapi/lib/server.js:341:16)","    at /Users/francescavarney/Development/Node/franvarney-api/node_modules/hapi/lib/server.js:266:14","    at done (/Users/francescavarney/Development/Node/franvarney-api/node_modules/hapi/node_modules/items/lib/index.js:31:25)","    at Server.finalize (/Users/francescavarney/Development/Node/franvarney-api/node_modules/hapi/lib/connection.js:172:9)","    at Server.g (events.js:260:16)","    at emitNone (events.js:72:20)","    at Server.emit (events.js:166:7)","    at emitListeningNT (net.js:1263:10)","    at nextTickCallbackWith1Arg (node.js:430:9)","    at process._tickCallback (node.js:352:17)"]}
```

![screen shot 2016-02-03 at 9 42 16 am](https://cloud.githubusercontent.com/assets/5891549/12785439/907e39d8-ca5a-11e5-90b3-ed4253b1804f.png)

Without formatting, I get: 

```
2016-02-03T14:15:28.511Z - info: Starting franvarney-api...
2016-02-03T14:15:28.527Z - info: Server starting at http://localhost:8000
2016-02-03T14:15:28.541Z - error: uncaughtException: Routes is not defined date=Wed Feb 03 2016 09:15:28 GMT-0500 (EST), pid=3944, uid=501, gid=20, cwd=/Users/francescavarney/Development/Node/franvarney-api, execPath=/Users/francescavarney/.nvm/versions/node/v4.2.6/bin/node, version=v4.2.6, argv=[/Users/francescavarney/.nvm/versions/node/v4.2.6/bin/node, /Users/francescavarney/Development/Node/franvarney-api/index], rss=153387008, heapTotal=127018080, heapUsed=101280176, loadavg=[1.740234375, 2.14111328125, 2.072265625], uptime=3216
ReferenceError: Routes is not defined
    at index.js:57:16
    at /Users/francescavarney/Development/Node/franvarney-api/node_modules/hapi/lib/server.js:274:20
    at [object Object].internals.Server.start.internals.Server.initialize.internals.Server._start.internals.Server.stop._invoke.internals.Server._invoke.next [as _invoke] (/Users/francescavarney/Development/Node/franvarney-api/node_modules/hapi/lib/server.js:341:16)
    at /Users/francescavarney/Development/Node/franvarney-api/node_modules/hapi/lib/server.js:266:14
    at done (/Users/francescavarney/Development/Node/franvarney-api/node_modules/hapi/node_modules/items/lib/index.js:31:25)
    at Server.finalize (/Users/francescavarney/Development/Node/franvarney-api/node_modules/hapi/lib/connection.js:172:9)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1263:10)
    at nextTickCallbackWith1Arg (node.js:430:9)
    at process._tickCallback (node.js:352:17)
```

![screen shot 2016-02-03 at 9 43 31 am](https://cloud.githubusercontent.com/assets/5891549/12785460/a3bce72e-ca5a-11e5-8d97-7d2a0262a1c0.png)

**Comment by jackboberg** [comment]
Maybe a conditional [around this](https://github.com/onmodulus/logger/blob/master/lib/formatter.js#L10)

```
if (process.env.NODE_ENV === 'production') out.push(JSON.stringify(data.meta));
else out.push(data.meta);
```

**Comment by franvarney** [comment]
It looks like disabling `handleExceptions` will output the readable error (second example), can you think of any reason why disabling this during development would be a bad idea?

**Comment by jackboberg** [comment]
make PR, happy to test it 😀
